export const qk = {
  exchanges: ["exchanges"] as const,
  calendar: ["calendar"] as const,
  symbols: (search: string, exchange?: string) => ["symbols", search, exchange ?? "all"] as const,
  candles: (id: string, tf: string) => ["candles", id, tf] as const,
  quote: (id: string) => ["quote", id] as const,
  quoteVerify: (id: string) => ["quoteVerify", id] as const,
  trend: (id: string, tf: string) => ["trend", id, tf] as const,
  levels: (id: string, tf: string) => ["levels", id, tf] as const,
  events: (id: string, tf: string) => ["events", id, tf] as const,
  orderBlocks: (id: string, tf: string) => ["orderBlocks", id, tf] as const,
  fvgs: (id: string, tf: string) => ["fvgs", id, tf] as const,
  sweeps: (id: string, tf: string) => ["sweeps", id, tf] as const,
  activeSetups: (id: string, tf: string) => ["activeSetups", id, tf] as const,
  historicalSetups: (id: string, tf: string) => ["historicalSetups", id, tf] as const,
  strategies: ["strategies"] as const,
  strategyDetail: (sid: string, id: string, tf: string) => ["strategyDetail", sid, id, tf] as const,
  analysis: (id: string, tf: string, plugin: string) => ["analysis", id, tf, plugin] as const,
  scanSetups: (id: string, tf: string) => ["scanSetups", id, tf] as const,
  scanTrend: (id: string, tf: string) => ["scanTrend", id, tf] as const,
};
